# Generated by Django 4.0.3 on 2022-05-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('wholesale_price', models.FloatField()),
                ('instore_price', models.FloatField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippingcompany',
            fields=[
                ('sc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sc_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ShippingCompany',
                'managed': False,
            },
        ),
    ]
