# Generated by Django 4.0.4 on 2022-05-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restockstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('restock_date', models.DateField()),
            ],
            options={
                'db_table': 'restockStore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restockwarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('restock_date', models.DateField()),
            ],
            options={
                'db_table': 'restockWarehouse',
                'managed': False,
            },
        ),
    ]
