# Generated by Django 4.0.4 on 2022-04-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateField()),
                ('billing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'memberAddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membercardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=20, unique=True)),
                ('card_name', models.CharField(max_length=30)),
                ('card_exp_month', models.IntegerField(null=True)),
                ('card_exp_year', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'memberCardInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('m', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.member')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
