# Generated by Django 4.0.4 on 2022-05-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_storeadmin_warehouseadmin_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
    ]
