# Generated by Django 4.0.4 on 2022-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instoreorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instoreOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onlineorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_type', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('card_info', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_num', models.BigIntegerField()),
                ('recipient_name', models.CharField(max_length=30)),
                ('recipient_phone', models.BigIntegerField()),
                ('tracking_num', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'onlineOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
            ],
            options={
                'db_table': 'orderList',
                'managed': False,
            },
        ),
    ]
